# Site settings
title: Kátia Nakamura
description: My Personal Website
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kátia Nakamura
user_title: Engineering Lead | Backend Dev
email: katiayn@gmail.com
twitter_username: KatiaNakamura
github_username:  katiayn

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
